export const PIXEL_COUNT = 8;
export const CANVAS_LARGE = 280;
export const CANVAS_MED = 160;

export const GRID_WIDTH = 224;
export const GRID_HEIGHT = 224;
export const PIXEL_SIZE = GRID_WIDTH/PIXEL_COUNT;
export const C_HEADER = 0;
export const ASM = 1;
export const HEX_PREFIX = '0x';

export const COMMENT_HEADER = "/*\n\n\tThis file was generated by GB_Pallete\n\tCreated By Sean Kelly\n\n*/\n\n\n"
export const LINE_WIDTH = 8;
export const ASM_PREFIX = '$';
export const VARIABLE_NAME = 'TileData';
